const SCREENS={
 home:{accent:'#7657ff',section:'AION CORE',title:'AION CORE',subtitle:'Единое пространство управления всей платформой',progress:54,request:'Усилить ядро решений',leftTitle:'AION CORE',leftDesc:'Центр управления всей платформой',coreTitle:'AION CORE',coreDesc:'Единое пространство управления всей платформой',nodes:[
  ['Проекты и задачи','Фокус исполнения','i-brief','#8b5cff','service',50,14],['Стратегические цели','Приоритеты владельца','i-target','#7b4dff','home',50,3],['Аналитика и отчёты','Данные и решения','i-chart','#735dff','home',76,18],['Решения и действия','Следующий шаг','i-bolt','#9a4fff','home',84,52],['Настройки и доступ','Безопасность','i-lock','#31d0a2','home',70,84],['Файлы и документы','Контекст и память','i-doc','#2b84ff','home',50,94],['Уведомления','Сигналы и события','i-bell','#ff9e35','home',23,82],['AI помощники','EVE и агенты','i-brain','#8c53ff','home',16,50]
 ]},
 service:{accent:'#5a62ff',section:'ПИЛОТ СЕРВИСНОЙ CRM',title:'Пилот сервисной CRM',subtitle:'Единое пространство сервисного бизнеса',progress:37,request:'Усилить контроль процесса',leftTitle:'Пилот сервисной CRM',leftDesc:'Единое пространство сервисного бизнеса',coreTitle:'Пилот сервисной CRM',coreDesc:'Единое пространство сервисного бизнеса',nodes:[
  ['Заявки и ремонты','Очередь сервиса','i-doc','#7b58ff','service',50,12],['Клиенты','История и связь','i-users','#7d69ff','service',76,20],['Склад и запчасти','Остатки и резерв','i-box','#3c8dff','service',84,48],['Оплата и касса','Платежи и долг','i-cash','#ff9f45','service',78,78],['Контроль качества','Проверка перед выдачей','i-shield','#7a67ff','service',64,91],['Мобильная приёмка','Быстрый приём','i-phone','#35c7ff','mobile',36,91],['Аналитика','Пульс сервиса','i-chart','#45a4ff','service',17,70],['Уведомления','Клиент и команда','i-bell','#9c63ff','service',15,38],['Приёмка','Старт заказа','i-brief','#6c75ff','service',25,18]
 ]},
 mobile:{accent:'#25cbe5',section:'МОБИЛЬНАЯ ПРИЁМКА',title:'Мобильная приёмка',subtitle:'Ускорение каждого шага на месте обращения клиента',progress:54,request:'Усилить скорость приёмки',leftTitle:'Мобильная приёмка',leftDesc:'Ускоренный контур приёмки на месте обращения клиента',coreTitle:'Мобильная приёмка',coreDesc:'Ускорение каждого шага на месте обращения клиента',nodes:[
  ['Экспресс-ремонт','Быстрый сценарий','i-bolt','#30baff','mobile',50,12],['QR-заказ','Статус клиента','i-qr','#35a8ff','mobile',77,20],['Отправка клиенту','Ссылка и QR','i-send','#40c8db','mobile',84,48],['Электронное согласие','Подтверждение условий','i-sign','#4dd6d1','mobile',76,79],['Подпись на дисплее','Электронная подпись','i-sign','#39b4ff','mobile',62,91],['Распознавание модели камерой','Без сохранения фото','i-camera','#2fb5ff','mobile',37,91],['Печать квитанции','Документы приёмки','i-printer','#39b4ff','mobile',17,72],['История и доказательства','Контроль событий','i-history','#4f8fff','mobile',16,40]
 ]}
};
let current='home',scale=1;
if('scrollRestoration' in history)history.scrollRestoration='manual';
function resetView(){const v=document.getElementById('viewport');if(v){v.scrollLeft=0;v.scrollTop=0}window.scrollTo(0,0);document.documentElement.scrollLeft=0;document.documentElement.scrollTop=0;document.body.scrollLeft=0;document.body.scrollTop=0}
function icon(id){return `<svg viewBox="0 0 64 64"><use href="#${id}"></use></svg>`}
function connections(nodes){return nodes.map(n=>`<line x1="50%" y1="49%" x2="${n[5]}%" y2="${n[6]}%"></line>`).join('')}
function nodeHtml(n,i){return `<div class="node" style="--x:${n[5]}%;--y:${n[6]}%;--node:${n[3]}"><button data-target="${n[4]}" data-index="${i}" aria-label="${n[0]}"><div class="pedestal"><div class="orb">${icon(n[2])}</div></div><strong>${n[0]}</strong><small>${n[1]}</small></button></div>`}
function chart(){return `<svg class="chart" viewBox="0 0 520 80" preserveAspectRatio="none"><line x1="0" y1="20" x2="520" y2="20"/><line x1="0" y1="40" x2="520" y2="40"/><line x1="0" y1="60" x2="520" y2="60"/><polyline stroke="#3fd3f4" points="0,57 40,53 80,59 120,42 160,44 200,30 240,34 280,20 320,27 360,16 400,22 440,10 480,15 520,8"/><polyline stroke="#7d5cff" points="0,63 40,60 80,61 120,56 160,52 200,55 240,43 280,46 320,37 360,41 400,34 440,28 480,32 520,23"/><polyline stroke="#48d9a6" points="0,66 40,64 80,63 120,62 160,58 200,61 240,55 280,52 320,50 360,45 400,47 440,40 480,38 520,35"/></svg>`}
function render(name){
 const s=SCREENS[name];document.documentElement.style.setProperty('--accent',s.accent);
 document.getElementById('screen').innerHTML=`
 <header class="topbar"><div class="brand">${icon('i-core')}<div>AION EVE<small>AI Living Platform</small></div></div><nav class="nav"><button class="${name==='home'?'active':''}" data-nav="home">Главная</button><button class="${name==='service'?'active':''}" data-nav="service">Миры</button><button>Проекты</button><button>Модули</button><button>Аналитика</button><button>Решения</button></nav><div class="user"><span>Тёмная</span><span>RU</span><span class="eve-orb">✦</span><span>Максим<br><small>Владелец</small></span></div></header>
 <section class="workspace">
  <aside class="panel side"><div class="eyebrow">AION EVE › ${name==='home'?'Главная':name==='service'?'Пилот сервисной CRM':'Мобильная приёмка'}</div><h1>${s.leftTitle}</h1><p>${s.leftDesc}</p><div class="status-card"><div class="status-row"><span class="dot"></span><b>${name==='home'?'Ядро активно':'Модуль активен'}</b></div><p>${name==='home'?'Система работает стабильно':'С 10 апреля 2024'}</p></div><div class="progress-row"><div class="ring" style="--p:${s.progress}"><b>${s.progress}%</b></div><div class="progress-copy"><b>${name==='home'?'Уровень доверия':'Зрелость модуля'}</b><small>${name==='home'?'Управление решениями под контролем':'Реальная работа сервиса с уровнем подтверждения'}</small></div></div><div class="bar" style="--p:${Math.min(82,s.progress+20)}%"><i></i></div><div class="side-foot">Осталось: ${name==='home'?'32 дня':'18 дней'}</div><div class="changes"><h3>Что изменилось</h3><div class="change"><span class="time">18:36</span><span>Обновлён рабочий контур</span></div><div class="change"><span class="time">17:25</span><span>Добавлено доказательство</span></div><div class="change"><span class="time">15:31</span><span>Закрыт следующий шаг</span></div><div class="change"><span class="time">14:11</span><span>Проверены зависимости</span></div></div></aside>
  <section class="panel map"><div class="map-head"><div><h2>Задачи и ремонты</h2><small>${s.subtitle}</small></div><small>Нажмите на светящийся объект</small></div><div class="universe"><div class="stars"></div><div class="orbit"></div><svg class="links">${connections(s.nodes)}</svg><div class="core">${icon(name==='home'?'i-core':name==='service'?'i-brief':'i-shield')}<div><h2>${s.coreTitle}</h2><p>${s.coreDesc}</p><em>● Активен</em></div></div>${s.nodes.map(nodeHtml).join('')}</div></section>
  <aside class="panel right"><div class="eve-head"><span class="eve-orb">✦</span><div><b>Иви рекомендует</b><small>Рекомендованное действие</small></div></div><div class="eve-card"><h3>${s.request}</h3><p>Есть смысл автоматизировать следующий шаг и проверить готовность перед масштабированием.</p><button>Просмотреть рекомендацию →</button></div><div class="eve-card next"><h3>Следующий шаг</h3><p>Настроить связанный модуль и проверить сценарий в реальной работе.</p><button>Перейти к шагу →</button></div><div class="eve-card risk"><h3>Риск</h3><p>Высокая нагрузка может замедлить выполнение. Нужна контрольная точка.</p><button>Смотреть детали →</button></div></aside>
 </section>
 <section class="bottom"><div class="panel"><div class="panel-title"><h3>Что изменилось</h3><small>смотреть всё</small></div><div class="event"><b>18:36</b><span>Обновлён рабочий контур</span></div><div class="event"><b>17:25</b><span>Добавлено доказательство</span></div><div class="event"><b>15:31</b><span>Закрыт следующий шаг</span></div><div class="event"><b>14:11</b><span>Проверены зависимости</span></div></div><div class="panel"><div class="panel-title"><h3>Пульс бизнеса</h3><small>7 дней</small></div><div class="kpis"><div class="kpi"><small>Заказы в работе</small><b>128</b></div><div class="kpi"><small>Завершено ремонтов</small><b>97</b></div><div class="kpi"><small>Средний срок ремонта</small><b>2,6 ч</b></div><div class="kpi"><small>NPS клиентов</small><b>72</b></div></div>${chart()}</div><div class="panel"><div class="panel-title"><h3>Доказательства и ресурсы</h3><small>смотреть всё</small></div><div class="resource"><span>Регламент мобильной приёмки</span><b>Документ</b></div><div class="resource"><span>Шаблон квитанции</span><b>Шаблон</b></div><div class="resource"><span>Инструкция распознавания модели</span><b>Отчёт</b></div><div class="resource"><span>Видео рабочего сценария</span><b>Видео</b></div></div></section>
 <footer class="footer"><span>AION EVE</span><div class="roadmap"><span><i>1</i>Закрепление актуальной системы</span><span><i>2</i>Интерактивный прототип</span><span><i>3</i>Реальный пилот</span><span><i>4</i>Мобильный MVP</span><span><i>5</i>Тестирование</span><span><i>6</i>Запуск</span></div><span>Система работает стабильно</span></footer>`;
 bind();fit();requestAnimationFrame(resetView);
}
function go(name){if(name===current){resetView();return}const canvas=document.getElementById('canvas');canvas.classList.add('changing');setTimeout(()=>{current=name;render(name);resetView();setTimeout(resetView,120);canvas.classList.remove('changing')},190)}
function bind(){
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));
 document.querySelectorAll('.node button').forEach(btn=>{
   const node=btn.closest('.node');
   btn.addEventListener('pointerdown',()=>{node.classList.add('touch');setTimeout(()=>node.classList.remove('touch'),520)},{passive:true});
   btn.addEventListener('click',()=>{node.classList.add('touch');setTimeout(()=>go(btn.dataset.target),190)});
 });
}
function fit(){const v=document.getElementById('viewport'),w=document.getElementById('canvasWrap'),c=document.getElementById('canvas');scale=Math.min(1,(v.clientWidth-2)/1440);w.style.width=(1440*scale)+'px';w.style.height=(c.offsetHeight*scale)+'px';c.style.transform=`scale(${scale})`;c.style.transformOrigin='top left'}
window.addEventListener('resize',()=>{fit();resetView()});window.addEventListener('pageshow',resetView);render('home');setTimeout(()=>document.getElementById('tip').style.display='none',6500);
